#:schema https://mise.jdx.dev/schema/mise-task.json

["fix:format"]
description = "Fix the formatting of the code"
depends = ["FMT_CHECK_ONLY=false fmt:?*"]

["fix"]
description = "Fix all the code, ensure all guidelines"
depends = ["fix:format"]
